name: Release

on:
  pull_request:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  checks:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: taiki-e/install-action@v2
      with:
        tool: just@1.40.0
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-${{ matrix.toolchain }}
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.88.0
        targets: x86_64-unknown-linux-musl,aarch64-unknown-linux-musl
    - name: Install musl tools
      run: |
        sudo apt-get install -y musl-tools
    - name: Build binary (x86 and ARM64)
      run: just build-binaries
    - name: Generate artifacts
      run: just release-artifacts
    - uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: artifacts/*
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*
        generate_release_notes: true
