name: Release

on:
  pull_request:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  checks:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest

        toolchain:
        - 1.77.2

    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1
      with:
        just-version: 1.25.2
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-${{ matrix.toolchain }}
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Install musl tools
      run: |
        sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl
    - name: Build Musl binary
      run: just cargo-build
    - name: Generate artifacts
      run: just release-artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: artifacts/*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*
        generate_release_notes: true
