name: Rust

on:
  push:
    tags:
      - 'v*'
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  checks:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

        toolchain:
        - 1.77.2
        - stable
        - nightly

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.25.2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2
      - name: Dependencies
        run: sudo apt install musl-tools -y
      - name: Compile application
        run: just cargo-compile
      - name: Build binary
        run: just cargo-build
      - name: Lint
        run: |
          just cargo-clippy-check
          just cargo-fmt-check
      - name: Artifacts
        run: just release-artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/*
          generate_release_notes: true
