name: Rust

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  checks:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest

        toolchain:
        - 1.88.0
        - stable
        - nightly

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.40.0
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2
      - name: Musl Dependencies
        run: sudo apt install musl-tools -y
        if: runner.os == 'Linux'
      - name: Build application
        run: just cargo-build
      - name: Lint
        run: |
          just cargo-clippy-check
          just cargo-fmt-check
        if: matrix.toolchain == '1.88.0'
